[phases.setup]
nixPkgs = ["python311", "nodejs_20", "gcc", "libjpeg-turbo", "zlib"]

[phases.install]
cmds = [
    "pip install uv",
    "uv sync",
    "cd backend && npm install"
]

[start]
cmd = "cd backend && node server.js"