// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/jobs": {
    params: {};
  };
  "/jobs/:jobId": {
    params: {
      "jobId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/jobs" | "/jobs/:jobId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/jobs.tsx": {
    id: "routes/jobs";
    page: "/jobs";
  };
  "routes/jobs.$jobId.tsx": {
    id: "routes/jobs.$jobId";
    page: "/jobs/:jobId";
  };
};